export const FAKE_POPULAR = [
  {
    adult: false,
    backdrop_path: "/lhdUwhInXu31qHm65jwBAlpTp8P.jpg",
    genre_ids: [10767],
    id: 82873,
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Kelly Clarkson Show",
    overview:
      "Kelly Clarkson presents the biggest newsmakers and names in film, television and music; as well as emerging new talent and everyday people who are beacons of hope in their communities.",
    popularity: 6090.584,
    poster_path: "/9Gg1oM8Us8gCS5aJA8e0ZRuIHnf.jpg",
    first_air_date: "2019-09-09",
    name: "The Kelly Clarkson Show",
    vote_average: 6.355,
    vote_count: 38,
  },
];

export const recommendations = [
  {
    adult: false,
    backdrop_path: "/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg",
    id: 60059,
    name: "Better Call Saul",
    original_language: "en",
    original_name: "Better Call Saul",
    overview:
      'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    poster_path: "/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 1831.962,
    first_air_date: "2015-02-08",
    vote_average: 8.666,
    vote_count: 4773,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 3152.356,
    first_air_date: "2011-04-17",
    vote_average: 8.447,
    vote_count: 22891,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    id: 66732,
    name: "Stranger Things",
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    media_type: "tv",
    genre_ids: [18, 10765, 9648],
    popularity: 392.642,
    first_air_date: "2016-07-15",
    vote_average: 8.613,
    vote_count: 16880,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/aSGSxGMTP893DPMCvMl9AdnEICE.jpg",
    id: 1405,
    name: "Dexter",
    original_language: "en",
    original_name: "Dexter",
    overview:
      "Dexter Morgan, a blood spatter pattern analyst for the Miami Metro Police also leads a secret life as a serial killer, hunting down criminals who have slipped through the cracks of justice.",
    poster_path: "/q8dWfc4JwQuv3HayIZeO84jAXED.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 390.863,
    first_air_date: "2006-10-01",
    vote_average: 8.191,
    vote_count: 3923,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/x4salpjB11umlUOltfNvSSrjSXm.jpg",
    id: 1402,
    name: "The Walking Dead",
    original_language: "en",
    original_name: "The Walking Dead",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    poster_path: "/n7PVu0hSz2sAsVekpOIoCnkWlbn.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10765],
    popularity: 2096.178,
    first_air_date: "2010-10-31",
    vote_average: 8.1,
    vote_count: 15936,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/4q6TBkY0Ilx7WtV5LX8HRqNHr5J.jpg",
    id: 19885,
    name: "Sherlock",
    original_language: "en",
    original_name: "Sherlock",
    overview:
      "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
    poster_path: "/7WTsnHkbA0FaG6R9twfFde0I9hl.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 9648],
    popularity: 407.714,
    first_air_date: "2010-07-25",
    vote_average: 8.523,
    vote_count: 5056,
    origin_country: ["GB"],
  },
  {
    adult: false,
    backdrop_path: "/rBF8wVQN8hTWHspVZBlI3h7HZJ.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 2731.732,
    first_air_date: "2013-12-02",
    vote_average: 8.7,
    vote_count: 9277,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    id: 1668,
    name: "Friends",
    original_language: "en",
    original_name: "Friends",
    overview:
      "Six young people from New York City, on their own and struggling to survive in the real world, find the companionship, comfort and support they get from each other to be the perfect antidote to the pressures of life.",
    poster_path: "/2koX1xLkpTQM4IZebYvKysFW1Nh.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 474.255,
    first_air_date: "1994-09-22",
    vote_average: 8.442,
    vote_count: 7621,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    id: 94605,
    name: "Arcane",
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    media_type: "tv",
    genre_ids: [16, 18, 10765, 10759],
    popularity: 132.634,
    first_air_date: "2021-11-06",
    vote_average: 8.748,
    vote_count: 3679,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/lHe8iwM4Cdm6RSEiara4PN8ZcBd.jpg",
    id: 44217,
    name: "Vikings",
    original_language: "en",
    original_name: "Vikings",
    overview:
      "The adventures of Ragnar Lothbrok, the greatest hero of his age. The series tells the sagas of Ragnar's band of Viking brothers and his family, as he rises to become King of the Viking tribes. As well as being a fearless warrior, Ragnar embodies the Norse traditions of devotion to the gods. Legend has it that he was a direct descendant of Odin, the god of war and warriors.",
    poster_path: "/bQLrHIRNEkE3PdIWQrZHynQZazu.jpg",
    media_type: "tv",
    genre_ids: [10759, 18, 10768],
    popularity: 625.22,
    first_air_date: "2013-03-03",
    vote_average: 8.093,
    vote_count: 6635,
    origin_country: ["CA"],
  },
];
